package nb9

import (
	"bytes"
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/smithy-go"
	"github.com/bokwoon95/nb9/sq"
	"golang.org/x/sync/errgroup"
)

var bufPool = sync.Pool{
	New: func() any { return &bytes.Buffer{} },
}

type FS interface {
	// WithContext returns a new FS with the given context.
	WithContext(context.Context) FS

	// Open opens the named file.
	Open(name string) (fs.File, error)

	// OpenWriter opens an io.WriteCloser that represents an instance of a
	// file. The parent directory must exist. If the file doesn't exist, it
	// should be created. If the file exists, its should be truncated.
	OpenWriter(name string, perm fs.FileMode) (io.WriteCloser, error)

	ReadDir(name string) ([]fs.DirEntry, error)

	// Mkdir creates a new directory with the specified name.
	Mkdir(name string, perm fs.FileMode) error

	MkdirAll(name string, perm fs.FileMode) error

	// Remove removes the named file or directory.
	Remove(name string) error

	RemoveAll(name string) error

	// Rename renames (moves) oldname to newname. If newname already exists and
	// is not a directory, Rename replaces it.
	Rename(oldname, newname string) error
}

type LocalFSConfig struct {
	// RootDir is the root directory of the LocalFS.
	RootDir string

	// TempDir is the temp directory of the LocalFS.
	TempDir string
}

// LocalFS represents a filesystem rooted on a local directory.
type LocalFS struct {
	// ctx provides the context of all operations called on the LocalFS.
	ctx context.Context

	// rootDir is the root directory of the LocalFS.
	rootDir string

	// tempDir is the temp directory of the LocalFS. Files are first written to
	// the tempDir before being swapped into the rootDir via an atomic rename
	// (windows is the exception I've found the renames there to be BUGGY AF!
	// *insert github issue where rename on windows keep failing intermittently
	// with an annoying permission error*)
	tempDir string
}

func NewLocalFS(config LocalFSConfig) *LocalFS {
	return &LocalFS{
		ctx:     context.Background(),
		rootDir: filepath.FromSlash(config.RootDir),
		tempDir: filepath.FromSlash(config.TempDir),
	}
}

func (fsys *LocalFS) WithContext(ctx context.Context) FS {
	return &LocalFS{
		ctx:     ctx,
		rootDir: fsys.rootDir,
		tempDir: fsys.tempDir,
	}
}

func (fsys *LocalFS) Open(name string) (fs.File, error) {
	err := fsys.ctx.Err()
	if err != nil {
		return nil, err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return nil, &fs.PathError{Op: "open", Path: name, Err: fs.ErrInvalid}
	}
	name = filepath.FromSlash(name)
	file, err := os.Open(filepath.Join(fsys.rootDir, name))
	if err != nil {
		return nil, err
	}
	return file, nil
}

func (fsys *LocalFS) OpenWriter(name string, _ fs.FileMode) (io.WriteCloser, error) {
	err := fsys.ctx.Err()
	if err != nil {
		return nil, err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return nil, &fs.PathError{Op: "openwriter", Path: name, Err: fs.ErrInvalid}
	}
	if runtime.GOOS == "windows" {
		file, err := os.OpenFile(filepath.Join(fsys.rootDir, name), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
		if err != nil {
			return nil, err
		}
		return file, nil
	}
	file := &LocalFileWriter{
		ctx:     fsys.ctx,
		rootDir: fsys.rootDir,
		tempDir: fsys.tempDir,
		name:    filepath.FromSlash(name),
	}
	if file.tempDir == "" {
		file.tempDir = os.TempDir()
	}
	file.tempFile, err = os.CreateTemp(file.tempDir, "__notebrewtemp*__")
	if err != nil {
		return nil, err
	}
	fileInfo, err := file.tempFile.Stat()
	if err != nil {
		return nil, err
	}
	file.tempName = fileInfo.Name()
	return file, nil
}

// LocalFileWriter represents a writable file on a LocalFS.
type LocalFileWriter struct {
	// ctx provides the context of all operations called on the file.
	ctx context.Context

	// rootDir is the root directory that houses the destination file.
	rootDir string

	// name is the name of the destination file relative to rootDir.
	name string

	// tempFile is temporary file we are writing to first before we do an
	// atomic rename into the destination file. This ensures that parallel
	// writers do not corrupt the destination file, writes are always all or
	// nothing and the last writer wins.
	tempFile *os.File

	// tempDir is the temp directory that houses the temporary file.
	tempDir string

	// tempName is the name of the temporary file relative to tempDir. It is
	// randomly generated by os.CreateTemp.
	tempName string

	// writeFailed records if any writes to the tempFile failed.
	writeFailed bool
}

func (file *LocalFileWriter) ReadFrom(r io.Reader) (n int64, err error) {
	err = file.ctx.Err()
	if err != nil {
		file.writeFailed = true
		return 0, err
	}
	n, err = file.tempFile.ReadFrom(r)
	if err != nil {
		file.writeFailed = true
		return n, err
	}
	return n, nil
}

func (file *LocalFileWriter) Write(p []byte) (n int, err error) {
	err = file.ctx.Err()
	if err != nil {
		file.writeFailed = true
		return 0, err
	}
	n, err = file.tempFile.Write(p)
	if err != nil {
		file.writeFailed = true
		return n, err
	}
	return n, nil
}

func (file *LocalFileWriter) Close() error {
	tempFilePath := filepath.Join(file.tempDir, file.tempName)
	destFilePath := filepath.Join(file.rootDir, file.name)
	defer os.Remove(tempFilePath)
	err := file.tempFile.Close()
	if err != nil {
		return err
	}
	if file.writeFailed {
		return nil
	}
	err = os.Rename(tempFilePath, destFilePath)
	if err != nil {
		return err
	}
	return nil
}

func (fsys *LocalFS) ReadDir(name string) ([]fs.DirEntry, error) {
	err := fsys.ctx.Err()
	if err != nil {
		return nil, err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return nil, &fs.PathError{Op: "mkdir", Path: name, Err: fs.ErrInvalid}
	}
	name = filepath.FromSlash(name)
	return os.ReadDir(filepath.Join(fsys.rootDir, name))
}

func (fsys *LocalFS) Mkdir(name string, _ fs.FileMode) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return &fs.PathError{Op: "mkdir", Path: name, Err: fs.ErrInvalid}
	}
	name = filepath.FromSlash(name)
	return os.Mkdir(filepath.Join(fsys.rootDir, name), 0755)
}

func (fsys *LocalFS) MkdirAll(name string, _ fs.FileMode) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return &fs.PathError{Op: "mkdirall", Path: name, Err: fs.ErrInvalid}
	}
	name = filepath.FromSlash(name)
	return os.MkdirAll(filepath.Join(fsys.rootDir, name), 0755)
}

func (fsys *LocalFS) Remove(name string) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return &fs.PathError{Op: "remove", Path: name, Err: fs.ErrInvalid}
	}
	name = filepath.FromSlash(name)
	return os.Remove(filepath.Join(fsys.rootDir, name))
}

func (fsys *LocalFS) RemoveAll(name string) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return &fs.PathError{Op: "removeall", Path: name, Err: fs.ErrInvalid}
	}
	name = filepath.FromSlash(name)
	return os.RemoveAll(filepath.Join(fsys.rootDir, name))
}

func (fsys *LocalFS) Rename(oldname, newname string) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(oldname) || strings.Contains(oldname, "\\") {
		return &fs.PathError{Op: "rename", Path: oldname, Err: fs.ErrInvalid}
	}
	if !fs.ValidPath(newname) || strings.Contains(newname, "\\") {
		return &fs.PathError{Op: "rename", Path: newname, Err: fs.ErrInvalid}
	}
	oldname = filepath.FromSlash(oldname)
	newname = filepath.FromSlash(newname)
	return os.Rename(filepath.Join(fsys.rootDir, oldname), filepath.Join(fsys.rootDir, newname))
}

type RemoteFSConfig struct {
	FilesDB        *sql.DB
	FilesDialect   string
	FilesErrorCode func(error) string
	Storage        Storage
	UsersDB        *sql.DB
	UsersDialect   string
}

type RemoteFS struct {
	ctx            context.Context
	filesDB        *sql.DB
	filesDialect   string
	filesErrorCode func(error) string
	storage        Storage
	usersDB        *sql.DB
	usersDialect   string
}

func NewRemoteFS(config RemoteFSConfig) *RemoteFS {
	return &RemoteFS{
		ctx:            context.Background(),
		filesDB:        config.FilesDB,
		filesDialect:   config.FilesDialect,
		filesErrorCode: config.FilesErrorCode,
		storage:        config.Storage,
		usersDB:        config.UsersDB,
		usersDialect:   config.UsersDialect,
	}
}

func (fsys *RemoteFS) WithContext(ctx context.Context) FS {
	return &RemoteFS{
		ctx:          ctx,
		filesDB:      fsys.filesDB,
		filesDialect: fsys.filesDialect,
		storage:      fsys.storage,
		usersDB:      fsys.usersDB,
		usersDialect: fsys.usersDialect,
	}
}

func (fsys *RemoteFS) Open(name string) (fs.File, error) {
	err := fsys.ctx.Err()
	if err != nil {
		return nil, err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return nil, &fs.PathError{Op: "open", Path: name, Err: fs.ErrInvalid}
	}
	if name == "." {
		file := &RemoteFile{
			ctx:     fsys.ctx,
			storage: fsys.storage,
			info:    &RemoteFileInfo{filePath: ".", isDir: true},
		}
		return file, nil
	}
	file, err := sq.FetchOne(fsys.ctx, fsys.filesDB, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "SELECT {*} FROM files WHERE file_path = {name}",
		Values: []any{
			sq.StringParam("name", name),
		},
	}, func(row *sq.Row) *RemoteFile {
		file := &RemoteFile{
			ctx:     fsys.ctx,
			storage: fsys.storage,
			info:    &RemoteFileInfo{},
		}
		row.UUID(&file.info.fileID, "file_id")
		file.info.filePath = row.String("file_path")
		file.info.isDir = row.Bool("is_dir")
		file.info.size = row.Int64("{}", sq.DialectExpression{
			Default: sq.Expr("COALESCE(OCTET_LENGTH(text), OCTET_LENGTH(data), size, 0)"),
			Cases: []sq.DialectCase{{
				Dialect: "sqlite",
				Result:  sq.Expr("COALESCE(LENGTH(CAST(text AS BLOB)), LENGTH(CAST(data AS BLOB)), size, 0)"),
			}},
		})
		file.info.modTime = row.Time("mod_time")
		buf := bufPool.Get().(*bytes.Buffer)
		buf.Reset()
		b := buf.Bytes()
		row.Scan(&b, "COALESCE(text, data)")
		if b != nil {
			file.buf = bytes.NewBuffer(b)
		}
		return file
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, &fs.PathError{Op: "open", Path: name, Err: fs.ErrNotExist}
		}
		return nil, err
	}
	return file, nil
}

type RemoteFileInfo struct {
	fileID   [16]byte
	filePath string
	isDir    bool
	size     int64
	modTime  time.Time
}

func (fileInfo *RemoteFileInfo) Name() string { return path.Base(fileInfo.filePath) }

func (fileInfo *RemoteFileInfo) Size() int64 { return fileInfo.size }

func (fileInfo *RemoteFileInfo) ModTime() time.Time { return fileInfo.modTime }

func (fileInfo *RemoteFileInfo) IsDir() bool { return fileInfo.isDir }

func (fileInfo *RemoteFileInfo) Sys() any { return nil }

func (fileInfo *RemoteFileInfo) Type() fs.FileMode { return fileInfo.Mode().Type() }

func (fileInfo *RemoteFileInfo) Info() (fs.FileInfo, error) { return fileInfo, nil }

func (fileInfo *RemoteFileInfo) Mode() fs.FileMode {
	if fileInfo.isDir {
		return fs.ModeDir
	}
	return 0
}

type RemoteFile struct {
	ctx        context.Context
	storage    Storage
	info       *RemoteFileInfo
	buf        *bytes.Buffer
	readCloser io.ReadCloser
}

func (file *RemoteFile) Stat() (fs.FileInfo, error) {
	return file.info, nil
}

func (file *RemoteFile) Read(p []byte) (n int, err error) {
	err = file.ctx.Err()
	if err != nil {
		return 0, err
	}
	if file.info.isDir {
		return 0, &fs.PathError{Op: "read", Path: file.info.filePath, Err: syscall.EISDIR}
	}
	if textExtensions[path.Ext(file.info.filePath)] {
		return file.buf.Read(p)
	}
	if file.readCloser == nil {
		file.readCloser, err = file.storage.Get(file.ctx, hex.EncodeToString(file.info.fileID[:])+path.Ext(file.info.filePath))
		if err != nil {
			return 0, err
		}
	}
	return file.readCloser.Read(p)
}

func (file *RemoteFile) Close() error {
	if file.info.isDir {
		return nil
	}
	if textExtensions[path.Ext(file.info.filePath)] {
		if file.buf == nil {
			return fs.ErrClosed
		}
		file.buf = nil
		return nil
	}
	if file.readCloser == nil {
		return fs.ErrClosed
	}
	err := file.readCloser.Close()
	if err != nil {
		return err
	}
	file.readCloser = nil
	return nil
}

func (fsys *RemoteFS) OpenWriter(name string, _ fs.FileMode) (io.WriteCloser, error) {
	err := fsys.ctx.Err()
	if err != nil {
		return nil, err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return nil, &fs.PathError{Op: "openwriter", Path: name, Err: fs.ErrInvalid}
	}
	if name == "." {
		return nil, &fs.PathError{Op: "openwriter", Path: name, Err: syscall.EISDIR}
	}
	file := &RemoteFileWriter{
		ctx:      fsys.ctx,
		db:       fsys.filesDB,
		dialect:  fsys.filesDialect,
		storage:  fsys.storage,
		filePath: name,
		modTime:  time.Now().UTC().Truncate(time.Second),
	}
	parentDir := path.Dir(file.filePath)
	if parentDir == "." {
		// If parentDir is the root directory, just fetch the file information
		// (if it exists).
		result, err := sq.FetchOne(fsys.ctx, fsys.filesDB, sq.Query{
			Dialect: fsys.filesDialect,
			Format:  "SELECT {*} FROM files WHERE file_path = {filePath}",
			Values: []any{
				sq.StringParam("filePath", file.filePath),
			},
		}, func(row *sq.Row) (result struct {
			fileID [16]byte
			isDir  bool
		}) {
			row.UUID(&result.fileID, "file_id")
			result.isDir = row.Bool("is_dir")
			return result
		})
		if err != nil {
			if !errors.Is(err, sql.ErrNoRows) {
				return nil, err
			}
		} else {
			if result.isDir {
				return nil, &fs.PathError{Op: "openwriter", Path: name, Err: syscall.EISDIR}
			}
			file.fileID = result.fileID
		}
	} else {
		results, err := sq.FetchAll(fsys.ctx, fsys.filesDB, sq.Query{
			Dialect: fsys.filesDialect,
			Format:  "SELECT {*} FROM files WHERE file_path IN ({parentDir}, {filePath})",
			Values: []any{
				sq.StringParam("parentDir", parentDir),
				sq.StringParam("filePath", file.filePath),
			},
		}, func(row *sq.Row) (result struct {
			fileID   [16]byte
			filePath string
			isDir    bool
		}) {
			row.UUID(&result.fileID, "file_id")
			result.filePath = row.String("file_path")
			result.isDir = row.Bool("is_dir")
			return result
		})
		if err != nil {
			return nil, err
		}
		for _, result := range results {
			switch result.filePath {
			case name:
				if result.isDir {
					return nil, &fs.PathError{Op: "openwriter", Path: name, Err: syscall.EISDIR}
				}
				file.fileID = result.fileID
			case parentDir:
				if !result.isDir {
					return nil, &fs.PathError{Op: "openwriter", Path: name, Err: syscall.ENOTDIR}
				}
				file.parentID = result.fileID
			}
		}
		if file.parentID == nil {
			return nil, &fs.PathError{Op: "openwriter", Path: name, Err: fs.ErrNotExist}
		}
	}
	if textExtensions[path.Ext(file.filePath)] {
		file.buf = bufPool.Get().(*bytes.Buffer)
		file.buf.Reset()
	} else {
		pipeReader, pipeWriter := io.Pipe()
		file.storageWriter = pipeWriter
		file.storageResult = make(chan error, 1)
		go func() {
			file.storageResult <- fsys.storage.Put(file.ctx, hex.EncodeToString(file.fileID[:])+path.Ext(file.filePath), pipeReader)
			close(file.storageResult)
		}()
	}
	return file, nil
}

type RemoteFileWriter struct {
	ctx            context.Context
	db             *sql.DB
	dialect        string
	storage        Storage
	fileID         [16]byte
	parentID       any // either nil or [16]byte
	filePath       string
	buf            *bytes.Buffer
	modTime        time.Time
	storageWriter  *io.PipeWriter
	storageWritten int
	storageResult  chan error
	writeFailed    bool
}

func (file *RemoteFileWriter) Write(p []byte) (n int, err error) {
	err = file.ctx.Err()
	if err != nil {
		file.writeFailed = true
		return 0, err
	}
	if textExtensions[path.Ext(file.filePath)] {
		n, err = file.buf.Write(p)
		if err != nil {
			file.writeFailed = true
		}
		return n, err
	}
	n, err = file.storageWriter.Write(p)
	file.storageWritten += n
	if err != nil {
		file.writeFailed = true
	}
	return n, err
}

func (file *RemoteFileWriter) Close() error {
	if textExtensions[path.Ext(file.filePath)] {
		defer bufPool.Put(file.buf)
	} else {
		file.storageWriter.Close()
		err := <-file.storageResult
		if err != nil {
			return err
		}
	}
	if file.writeFailed {
		return nil
	}

	// If file exists, just have to update the file entry in the database.
	if file.fileID != [16]byte{} {
		if textExtensions[path.Ext(file.filePath)] {
			if isFulltextIndexed(file.filePath) {
				_, err := sq.Exec(file.ctx, file.db, sq.Query{
					Dialect: file.dialect,
					Format:  "UPDATE files SET text = {text}, data = NULL, size = NULL, mod_time = {modTime} WHERE file_id = {fileID}",
					Values: []any{
						sq.BytesParam("text", file.buf.Bytes()),
						sq.Param("modTime", sq.Timestamp{Time: file.modTime, Valid: true}),
						sq.UUIDParam("fileID", file.fileID),
					},
				})
				if err != nil {
					return err
				}
			} else {
				_, err := sq.Exec(file.ctx, file.db, sq.Query{
					Dialect: file.dialect,
					Format:  "UPDATE files SET text = NULL, data = {data}, size = NULL, mod_time = {modTime} WHERE file_id = {fileID}",
					Values: []any{
						sq.BytesParam("data", file.buf.Bytes()),
						sq.Param("modTime", sq.Timestamp{Time: file.modTime, Valid: true}),
						sq.UUIDParam("fileID", file.fileID),
					},
				})
				if err != nil {
					return err
				}
			}
		} else {
			_, err := sq.Exec(file.ctx, file.db, sq.Query{
				Dialect: file.dialect,
				Format:  "UPDATE files SET text = NULL, data = NULL, size = {size}, mod_time = {modTime} WHERE file_id = {fileID}",
				Values: []any{
					sq.IntParam("size", file.storageWritten),
					sq.Param("modTime", sq.Timestamp{Time: file.modTime, Valid: true}),
					sq.UUIDParam("fileID", file.fileID),
				},
			})
			if err != nil {
				return err
			}
		}
		return nil
	}

	// If we reach here it means file doesn't exist. Insert a new file entry
	// into the database.
	tx, err := file.db.BeginTx(file.ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if textExtensions[path.Ext(file.filePath)] {
		if isFulltextIndexed(file.filePath) {
			_, err := sq.Exec(file.ctx, tx, sq.Query{
				Dialect: file.dialect,
				Format: "INSERT INTO files (file_id, parent_id, file_path, is_dir, text, mod_time)" +
					" VALUES ({fileID}, {parentID}, {filePath}, {isDir}, {text}, {modTime})",
				Values: []any{
					sq.UUIDParam("fileID", NewID()),
					sq.UUIDParam("parentID", file.parentID),
					sq.StringParam("filePath", file.filePath),
					sq.BoolParam("isDir", false),
					sq.BytesParam("text", file.buf.Bytes()),
					sq.Param("modTime", sq.Timestamp{Time: file.modTime, Valid: true}),
				},
			})
			if err != nil {
				return err
			}
		} else {
			_, err := sq.Exec(file.ctx, tx, sq.Query{
				Dialect: file.dialect,
				Format: "INSERT INTO files (file_id, parent_id, file_path, is_dir, data, mod_time)" +
					" VALUES ({fileID}, {parentID}, {filePath}, {isDir}, {data}, {modTime})",
				Values: []any{
					sq.UUIDParam("fileID", NewID()),
					sq.UUIDParam("parentID", file.parentID),
					sq.StringParam("filePath", file.filePath),
					sq.BoolParam("isDir", false),
					sq.BytesParam("data", file.buf.Bytes()),
					sq.Param("modTime", sq.Timestamp{Time: file.modTime, Valid: true}),
				},
			})
			if err != nil {
				return err
			}
		}
	} else {
		_, err := sq.Exec(file.ctx, tx, sq.Query{
			Dialect: file.dialect,
			Format: "INSERT INTO files (file_id, parent_id, file_path, is_dir, size, mod_time)" +
				" VALUES ({fileID}, {parentID}, {filePath}, {isDir}, {size}, {modTime})",
			Values: []any{
				sq.UUIDParam("fileID", NewID()),
				sq.UUIDParam("parentID", file.parentID),
				sq.StringParam("filePath", file.filePath),
				sq.BoolParam("isDir", false),
				sq.IntParam("size", file.storageWritten),
				sq.Param("modTime", sq.Timestamp{Time: file.modTime, Valid: true}),
			},
		})
		if err != nil {
			go file.storage.Delete(context.Background(), hex.EncodeToString(file.fileID[:])+path.Ext(file.filePath))
			return err
		}
	}
	if file.parentID != nil {
		_, err := sq.Exec(file.ctx, tx, sq.Query{
			Dialect: file.dialect,
			Format:  "UPDATE files SET num_files = num_files + 1 WHERE file_id = {parentID}",
			Values: []any{
				sq.UUIDParam("parentID", file.parentID),
			},
		})
		if err != nil {
			return err
		}
	}
	err = tx.Commit()
	if err != nil {
		return err
	}
	return nil
}

func (fsys *RemoteFS) ReadDir(name string) ([]fs.DirEntry, error) {
	err := fsys.ctx.Err()
	if err != nil {
		return nil, err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return nil, &fs.PathError{Op: "readdir", Path: name, Err: fs.ErrInvalid}
	}
	var condition sq.Expression
	if name == "." {
		condition = sq.Expr("parent_id IS NULL")
	} else {
		condition = sq.Expr("parent_id = (SELECT file_id FROM files WHERE file_path = {})", name)
	}
	dirEntries, err := sq.FetchAll(fsys.ctx, fsys.filesDB, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "SELECT {*} FROM files WHERE {condition}",
		Values: []any{
			sq.Param("condition", condition),
		},
	}, func(row *sq.Row) fs.DirEntry {
		file := &RemoteFileInfo{}
		row.UUID(&file.fileID, "file_id")
		file.filePath = row.String("file_path")
		file.isDir = row.Bool("is_dir")
		file.size = row.Int64("{}", sq.DialectExpression{
			Default: sq.Expr("COALESCE(OCTET_LENGTH(text), OCTET_LENGTH(data), size, 0)"),
			Cases: []sq.DialectCase{{
				Dialect: "sqlite",
				Result:  sq.Expr("COALESCE(LENGTH(CAST(text AS BLOB)), LENGTH(CAST(data AS BLOB)), size, 0)"),
			}},
		})
		file.modTime = row.Time("mod_time")
		return file
	})
	if err != nil {
		return nil, err
	}
	return dirEntries, nil
}

func (fsys *RemoteFS) Mkdir(name string, _ fs.FileMode) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return &fs.PathError{Op: "mkdir", Path: name, Err: fs.ErrInvalid}
	}
	if name == "." {
		return nil
	}
	modTime := time.Now().UTC().Truncate(time.Second)
	parentDir := path.Dir(name)
	if parentDir == "." {
		_, err := sq.Exec(fsys.ctx, fsys.filesDB, sq.Query{
			Dialect: fsys.filesDialect,
			Format: "INSERT INTO files (file_id, file_path, is_dir, mod_time)" +
				" VALUES ({fileID}, {filePath}, {isDir}, {modTime})",
			Values: []any{
				sq.UUIDParam("fileID", NewID()),
				sq.StringParam("filePath", name),
				sq.BoolParam("isDir", true),
				sq.Param("modTime", sq.Timestamp{Time: modTime, Valid: true}),
			},
		})
		if err != nil {
			if fsys.filesErrorCode == nil {
				return err
			}
			errcode := fsys.filesErrorCode(err)
			if IsKeyViolation(fsys.filesDialect, errcode) {
				return &fs.PathError{Op: "mkdir", Path: name, Err: fs.ErrExist}
			}
			return err
		}
	} else {
		_, err = sq.Exec(fsys.ctx, fsys.filesDB, sq.Query{
			Dialect: fsys.filesDialect,
			Format: "INSERT INTO files (file_id, parent_id, file_path, is_dir, mod_time)" +
				" VALUES ({fileID}, (select file_id FROM files WHERE file_path = {parentDir}), {filePath}, {isDir}, {modTime})",
			Values: []any{
				sq.UUIDParam("fileID", NewID()),
				sq.StringParam("parentDir", parentDir),
				sq.StringParam("filePath", name),
				sq.BoolParam("isDir", true),
				sq.Param("modTime", sq.Timestamp{Time: modTime, Valid: true}),
			},
		})
		if err != nil {
			if fsys.filesErrorCode == nil {
				return err
			}
			errcode := fsys.filesErrorCode(err)
			if IsKeyViolation(fsys.filesDialect, errcode) {
				return &fs.PathError{Op: "mkdir", Path: name, Err: fs.ErrExist}
			}
			return err
		}
	}
	return nil
}

func (fsys *RemoteFS) MkdirAll(name string, _ fs.FileMode) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") {
		return &fs.PathError{Op: "mkdirall", Path: name, Err: fs.ErrInvalid}
	}
	if name == "." {
		return nil
	}
	conn, err := fsys.filesDB.Conn(fsys.ctx)
	if err != nil {
		return err
	}
	defer conn.Close()

	// Insert the top level directory (no parent), ignoring duplicates.
	modTime := time.Now().UTC().Truncate(time.Second)
	segments := strings.Split(name, "/")
	switch fsys.filesDialect {
	case "sqlite", "postgres":
		_, err := sq.Exec(fsys.ctx, conn, sq.Query{
			Dialect: fsys.filesDialect,
			Format: "INSERT INTO files (file_id, file_path, is_dir, mod_time)" +
				" VALUES ({fileID}, {filePath}, {isDir}, {modTime})" +
				" ON CONFLICT DO NOTHING",
			Values: []any{
				sq.UUIDParam("fileID", NewID()),
				sq.StringParam("filePath", segments[0]),
				sq.BoolParam("isDir", true),
				sq.Param("modTime", sq.Timestamp{Time: modTime, Valid: true}),
			},
		})
		if err != nil {
			return err
		}
	case "mysql":
		_, err := sq.Exec(fsys.ctx, conn, sq.Query{
			Dialect: fsys.filesDialect,
			Format: "INSERT INTO files (file_id, file_path, is_dir, mod_time)" +
				" VALUES ({fileID}, {filePath}, {isDir}, {modTime})" +
				" ON DUPLICATE KEY UPDATE file_id = file_id",
			Values: []any{
				sq.UUIDParam("fileID", NewID()),
				sq.StringParam("filePath", segments[0]),
				sq.BoolParam("isDir", true),
				sq.Param("modTime", sq.Timestamp{Time: modTime, Valid: true}),
			},
		})
		if err != nil {
			return err
		}
	default:
		return fmt.Errorf("unsupported dialect %q", fsys.filesDialect)
	}

	// Insert the rest of the directories, ignoring duplicates.
	if len(segments) > 1 {
		var preparedExec *sq.PreparedExec
		switch fsys.filesDialect {
		case "sqlite", "postgres":
			preparedExec, err = sq.PrepareExec(fsys.ctx, conn, sq.Query{
				Dialect: fsys.filesDialect,
				Format: "INSERT INTO files (file_id, parent_id, file_path, is_dir, mod_time)" +
					" VALUES ({fileID}, (select file_id FROM files WHERE file_path = {parentDir}), {filePath}, {isDir}, {modTime})" +
					" ON CONFLICT DO NOTHING",
				Values: []any{
					sq.Param("fileID", nil),
					sq.Param("parentDir", nil),
					sq.Param("filePath", nil),
					sq.Param("isDir", nil),
					sq.Param("modTime", nil),
				},
			})
			if err != nil {
				return err
			}
		case "mysql":
			preparedExec, err = sq.PrepareExec(fsys.ctx, conn, sq.Query{
				Dialect: fsys.filesDialect,
				Format: "INSERT INTO files (file_id, parent_id, file_path, is_dir, mod_time)" +
					" VALUES ({fileID}, (select file_id FROM files WHERE file_path = {parentDir}), {filePath}, {isDir}, {modTime})" +
					" ON DUPLICATE KEY UPDATE file_id = file_id",
				Values: []any{
					sq.Param("fileID", nil),
					sq.Param("parentDir", nil),
					sq.Param("filePath", nil),
					sq.Param("isDir", nil),
					sq.Param("modTime", nil),
				},
			})
			if err != nil {
				return err
			}
		default:
			return fmt.Errorf("unsupported dialect %q", fsys.filesDialect)
		}
		defer preparedExec.Close()
		for i := 1; i < len(segments); i++ {
			parentDir := path.Join(segments[:i]...)
			filePath := path.Join(segments[:i+1]...)
			_, err := preparedExec.Exec(fsys.ctx,
				sq.UUIDParam("fileID", NewID()),
				sq.StringParam("parentDir", parentDir),
				sq.StringParam("filePath", filePath),
				sq.BoolParam("isDir", true),
				sq.Param("modTime", sq.Timestamp{Time: modTime, Valid: true}),
			)
			if err != nil {
				return err
			}
		}
		err = preparedExec.Close()
		if err != nil {
			return err
		}
	}
	return nil
}

func (fsys *RemoteFS) Remove(name string) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") || name == "." {
		return &fs.PathError{Op: "remove", Path: name, Err: fs.ErrInvalid}
	}
	file, err := sq.FetchOne(fsys.ctx, fsys.filesDB, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "SELECT {*} FROM files WHERE file_path = {name}",
		Values: []any{
			sq.StringParam("name", name),
		},
	}, func(row *sq.Row) (file struct {
		fileID       [16]byte
		filePath     string
		isDir        bool
		isStoredInDB bool
		hasChildren  bool
	}) {
		row.UUID(&file.fileID, "file_id")
		file.filePath = row.String("file_path")
		file.isDir = row.Bool("is_dir")
		file.isStoredInDB = row.Bool("text IS NOT NULL OR data IS NOT NULL")
		file.hasChildren = row.Bool("EXISTS (SELECT 1 FROM files WHERE file_path LIKE {pattern} ESCAPE '\\')", sq.StringParam("pattern", strings.NewReplacer("%", "\\%", "_", "\\_").Replace(name)+"/%"))
		return file
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return &fs.PathError{Op: "remove", Path: name, Err: fs.ErrNotExist}
		}
		return err
	}
	if file.hasChildren {
		return &fs.PathError{Op: "remove", Path: name, Err: syscall.ENOTEMPTY}
	}
	if !file.isStoredInDB {
		err = fsys.storage.Delete(fsys.ctx, hex.EncodeToString(file.fileID[:])+path.Ext(file.filePath))
		if err != nil {
			return err
		}
	}
	tx, err := fsys.filesDB.BeginTx(fsys.ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	// NOTE: For SQLite and Postgres, we can reduce the number of queries to 2
	// (current is 3) by using DELETE ... RETURNING. Do this if Remove() proves
	// to be too slow.
	_, err = sq.Exec(fsys.ctx, tx, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "DELETE FROM files WHERE file_path = {name}",
		Values: []any{
			sq.StringParam("name", name),
		},
	})
	if err != nil {
		return err
	}
	if !file.isDir {
		parentDir := path.Dir(name)
		if parentDir != "." {
			_, err = sq.Exec(fsys.ctx, tx, sq.Query{
				Dialect: fsys.filesDialect,
				Format:  "UPDATE files SET num_files = num_files - 1 WHERE file_path = {parentDir} AND num_files > 0",
				Values: []any{
					sq.StringParam("parentDir", parentDir),
				},
			})
			if err != nil {
				return err
			}
		}
	}
	err = tx.Commit()
	if err != nil {
		return err
	}
	return nil
}

func (fsys *RemoteFS) RemoveAll(name string) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(name) || strings.Contains(name, "\\") || name == "." {
		return &fs.PathError{Op: "removeall", Path: name, Err: fs.ErrInvalid}
	}
	pattern := strings.NewReplacer("%", "\\%", "_", "\\_").Replace(name) + "/%"
	files, err := sq.FetchAll(fsys.ctx, fsys.filesDB, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "SELECT {*} FROM files WHERE (file_path = {name} OR file_path LIKE {pattern} ESCAPE '\\') AND text IS NULL AND data IS NULL",
		Values: []any{
			sq.StringParam("name", name),
			sq.StringParam("pattern", pattern),
		},
	}, func(row *sq.Row) (file struct {
		fileID   [16]byte
		filePath string
	}) {
		row.UUID(&file.fileID, "file_id")
		file.filePath = row.String("file_path")
		return file
	})
	g, ctx := errgroup.WithContext(fsys.ctx)
	for _, file := range files {
		file := file
		g.Go(func() error {
			return fsys.storage.Delete(ctx, hex.EncodeToString(file.fileID[:])+path.Ext(file.filePath))
		})
	}
	err = g.Wait()
	if err != nil {
		return err
	}
	tx, err := fsys.filesDB.BeginTx(fsys.ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	_, err = sq.Exec(fsys.ctx, tx, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "DELETE FROM files WHERE file_path LIKE {pattern} ESCAPE '\\'",
		Values: []any{
			sq.StringParam("pattern", pattern),
		},
	})
	if err != nil {
		return err
	}
	isDir, err := sq.FetchOne(fsys.ctx, tx, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "SELECT {*} FROM files WHERE file_path = {name}",
		Values: []any{
			sq.StringParam("name", name),
		},
	}, func(row *sq.Row) bool {
		return row.Bool("is_dir")
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}
		return err
	}
	// NOTE: For SQLite and Postgres, we can reduce the number of queries to 2
	// (current is 5) by using DELETE ... RETURNING. Do this if RemoveAll()
	// proves to be too slow.
	_, err = sq.Exec(fsys.ctx, tx, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "DELETE FROM files WHERE file_path = {name}",
		Values: []any{
			sq.StringParam("name", name),
		},
	})
	if err != nil {
		return err
	}
	if !isDir {
		parentDir := path.Dir(name)
		if parentDir != "." {
			_, err = sq.Exec(fsys.ctx, tx, sq.Query{
				Dialect: fsys.filesDialect,
				Format:  "UPDATE files SET num_files = num_files - 1 WHERE file_path = {parentDir} AND num_files > 0",
				Values: []any{
					sq.StringParam("parentDir", parentDir),
				},
			})
			if err != nil {
				return err
			}
		}
	}
	err = tx.Commit()
	if err != nil {
		return err
	}
	return nil
}

func (fsys *RemoteFS) Rename(oldname, newname string) error {
	err := fsys.ctx.Err()
	if err != nil {
		return err
	}
	if !fs.ValidPath(oldname) || strings.Contains(oldname, "\\") {
		return &fs.PathError{Op: "rename", Path: oldname, Err: fs.ErrInvalid}
	}
	if !fs.ValidPath(newname) || strings.Contains(newname, "\\") {
		return &fs.PathError{Op: "rename", Path: newname, Err: fs.ErrInvalid}
	}
	modTime := sq.Timestamp{
		Time:  time.Now().UTC().Truncate(time.Second),
		Valid: true,
	}
	tx, err := fsys.filesDB.BeginTx(fsys.ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	oldnameIsDir, err := sq.FetchOne(fsys.ctx, tx, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "SELECT {*} FROM files WHERE file_path = {oldname}",
		Values: []any{
			sq.StringParam("oldname", oldname),
		},
	}, func(row *sq.Row) bool {
		return row.Bool("is_dir")
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return &fs.PathError{Op: "rename", Path: oldname, Err: fs.ErrNotExist}
		}
		return err
	}
	if !oldnameIsDir && textExtensions[path.Ext(oldname)] != textExtensions[path.Ext(newname)] {
		return fmt.Errorf("cannot rename file from %q to %q because their extensions are not compatible", oldname, newname)
	}
	_, err = sq.Exec(fsys.ctx, tx, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "DELETE FROM files WHERE file_path = {newname} AND NOT is_dir",
		Values: []any{
			sq.StringParam("newname", newname),
		},
	})
	if err != nil {
		return err
	}
	var updateTextOrData sq.Expression
	if !oldnameIsDir && textExtensions[path.Ext(oldname)] && textExtensions[path.Ext(newname)] {
		if !isFulltextIndexed(oldname) && isFulltextIndexed(newname) {
			switch fsys.filesDialect {
			case "sqlite":
				updateTextOrData = sq.Expr(", text = data, data = NULL")
			case "postgres":
				updateTextOrData = sq.Expr(", text = convert_from(data, 'UTF8'), data = NULL")
			case "mysql":
				updateTextOrData = sq.Expr(", text = convert(data USING utf8mb4), data = NULL")
			}
		} else if isFulltextIndexed(oldname) && !isFulltextIndexed(newname) {
			switch fsys.filesDialect {
			case "sqlite":
				updateTextOrData = sq.Expr(", data = text, text = NULL")
			case "postgres":
				updateTextOrData = sq.Expr(", data = convert_to(text, 'UTF8'), text = NULL")
			case "mysql":
				updateTextOrData = sq.Expr(", data = convert(text USING BINARY), text = NULL")
			}
		}
	}
	_, err = sq.Exec(fsys.ctx, tx, sq.Query{
		Dialect: fsys.filesDialect,
		Format:  "UPDATE files SET file_path = {newname}, mod_time = {modTime} {updateTextOrData} WHERE file_path = {oldname}",
		Values: []any{
			sq.StringParam("newname", newname),
			sq.Param("modTime", modTime),
			sq.Param("updateTextOrData", updateTextOrData),
			sq.StringParam("oldname", oldname),
		},
	})
	if err != nil {
		// We weren't able to delete {newname} earlier, which means it is a
		// directory.
		if fsys.filesErrorCode == nil {
			return err
		}
		errcode := fsys.filesErrorCode(err)
		if IsKeyViolation(fsys.filesDialect, errcode) {
			return &fs.PathError{Op: "rename", Path: newname, Err: syscall.EISDIR}
		}
		return err
	}
	if oldnameIsDir {
		_, err = sq.Exec(fsys.ctx, tx, sq.Query{
			Dialect: fsys.filesDialect,
			Format:  "UPDATE files SET file_path = {newFilePath}, mod_time = {modTime} WHERE file_path LIKE {pattern} ESCAPE '\\'",
			Values: []any{
				sq.Param("newFilePath", sq.DialectExpression{
					Default: sq.Expr("{} || SUBSTR(file_path, {})", newname, len(oldname)+1),
					Cases: []sq.DialectCase{{
						Dialect: "mysql",
						Result:  sq.Expr("CONCAT({}, SUBSTR(file_path, {}))", newname, len(oldname)+1),
					}},
				}),
				sq.Param("modTime", modTime),
				sq.StringParam("pattern", strings.NewReplacer("%", "\\%", "_", "\\_").Replace(oldname)+"/%"),
			},
		})
		if err != nil {
			return err
		}
	}
	err = tx.Commit()
	if err != nil {
		return err
	}
	return nil
}

type Storage interface {
	Get(ctx context.Context, key string) (io.ReadCloser, error)
	Put(ctx context.Context, key string, reader io.Reader) error
	Delete(ctx context.Context, key string) error
}

type S3Storage struct {
	Client *s3.Client
	Bucket string
}

var _ Storage = (*S3Storage)(nil)

type S3StorageConfig struct {
	Endpoint        string `json:"endpoint,omitempty"`
	Region          string `json:"region,omitempty"`
	Bucket          string `json:"bucket,omitempty"`
	AccessKeyID     string `json:"accessKeyID,omitempty"`
	SecretAccessKey string `json:"secretAccessKey,omitempty"`
}

func NewS3Storage(ctx context.Context, config S3StorageConfig) (*S3Storage, error) {
	storage := &S3Storage{
		Client: s3.New(s3.Options{
			BaseEndpoint: aws.String(config.Endpoint),
			Region:       config.Region,
			Credentials:  aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider(config.AccessKeyID, config.SecretAccessKey, "")),
		}),
		Bucket: config.Bucket,
	}
	// Ping the bucket and see if we have access.
	_, err := storage.Client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{
		Bucket:  &storage.Bucket,
		MaxKeys: aws.Int32(1),
	})
	if err != nil {
		return nil, err
	}
	return storage, nil
}

func (storage *S3Storage) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	output, err := storage.Client.GetObject(ctx, &s3.GetObjectInput{
		Bucket: &storage.Bucket,
		Key:    aws.String(key),
	})
	if err != nil {
		var apiErr smithy.APIError
		if errors.As(err, &apiErr) {
			if apiErr.ErrorCode() == "NoSuchKey" {
				return nil, &fs.PathError{Op: "get", Path: key, Err: fs.ErrNotExist}
			}
		}
		return nil, err
	}
	return output.Body, nil
}

func (storage *S3Storage) Put(ctx context.Context, key string, reader io.Reader) error {
	_, err := storage.Client.PutObject(ctx, &s3.PutObjectInput{
		Bucket: &storage.Bucket,
		Key:    aws.String(key),
		Body:   reader,
	})
	if err != nil {
		return err
	}
	return nil
}

func (storage *S3Storage) Delete(ctx context.Context, key string) error {
	_, err := storage.Client.DeleteObject(ctx, &s3.DeleteObjectInput{
		Bucket: &storage.Bucket,
		Key:    aws.String(key),
	})
	if err != nil {
		return err
	}
	return nil
}

type InMemoryStorage struct {
	mu      sync.RWMutex
	entries map[string][]byte
}

var _ Storage = (*InMemoryStorage)(nil)

func NewInMemoryStorage() *InMemoryStorage {
	return &InMemoryStorage{
		mu:      sync.RWMutex{},
		entries: make(map[string][]byte),
	}
}

func (storage *InMemoryStorage) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	storage.mu.RLock()
	value, ok := storage.entries[key]
	storage.mu.RUnlock()
	if !ok {
		return nil, &fs.PathError{Op: "get", Path: key, Err: fs.ErrNotExist}
	}
	return io.NopCloser(bytes.NewReader(value)), nil
}

func (storage *InMemoryStorage) Put(ctx context.Context, key string, reader io.Reader) error {
	value, err := io.ReadAll(reader)
	if err != nil {
		return err
	}
	storage.mu.Lock()
	storage.entries[key] = value
	storage.mu.Unlock()
	return nil
}

func (storage *InMemoryStorage) Delete(ctx context.Context, key string) error {
	storage.mu.Lock()
	delete(storage.entries, key)
	storage.mu.Unlock()
	return nil
}

type FileStorage struct {
	rootDir string
	tempDir string
}

func NewFileStorage(rootDir, tempDir string) *FileStorage {
	return &FileStorage{
		rootDir: filepath.FromSlash(rootDir),
		tempDir: filepath.FromSlash(tempDir),
	}
}

func (storage *FileStorage) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	err := ctx.Err()
	if err != nil {
		return nil, err
	}
	if len(key) < 4 {
		return nil, &fs.PathError{Op: "get", Path: key, Err: fs.ErrInvalid}
	}
	file, err := os.Open(filepath.Join(storage.rootDir, key[:4], key))
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, &fs.PathError{Op: "get", Path: key, Err: fs.ErrNotExist}
		}
		return nil, err
	}
	return file, nil
}

func (storage *FileStorage) Put(ctx context.Context, key string, reader io.Reader) error {
	err := ctx.Err()
	if err != nil {
		return err
	}
	if len(key) < 4 {
		return &fs.PathError{Op: "put", Path: key, Err: fs.ErrInvalid}
	}
	if runtime.GOOS == "windows" {
		file, err := os.OpenFile(filepath.Join(storage.rootDir, key[:4], key), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
		if err != nil {
			return err
		}
		_, err = io.Copy(file, reader)
		if err != nil {
			return err
		}
		return nil
	}
	tempDir := storage.tempDir
	if tempDir == "" {
		tempDir = os.TempDir()
	}
	tempFile, err := os.CreateTemp(tempDir, "__notebrewtemp*__")
	if err != nil {
		return err
	}
	fileInfo, err := tempFile.Stat()
	if err != nil {
		return err
	}
	tempFilePath := filepath.Join(tempDir, fileInfo.Name())
	destFilePath := filepath.Join(storage.rootDir, key[:4], key)
	defer os.Remove(tempFilePath)
	defer tempFile.Close()
	_, err = io.Copy(tempFile, reader)
	if err != nil {
		return err
	}
	err = tempFile.Close()
	if err != nil {
		return err
	}
	err = os.Rename(tempFilePath, destFilePath)
	if err != nil {
		if !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		err := os.Mkdir(filepath.Join(storage.rootDir, key[:4]), 0755)
		if err != nil && !errors.Is(err, fs.ErrExist) {
			return err
		}
		err = os.Rename(tempFilePath, destFilePath)
		if err != nil {
			return err
		}
	}
	return nil
}

func (storage *FileStorage) Delete(ctx context.Context, key string) error {
	err := ctx.Err()
	if err != nil {
		return err
	}
	if len(key) < 4 {
		return &fs.PathError{Op: "delete", Path: key, Err: fs.ErrInvalid}
	}
	err = os.Remove(filepath.Join(storage.rootDir, key[:4], key))
	if err != nil {
		return err
	}
	return nil
}

func NewID() [16]byte {
	var timestamp [8]byte
	binary.BigEndian.PutUint64(timestamp[:], uint64(time.Now().Unix()))
	var id [16]byte
	copy(id[:5], timestamp[len(timestamp)-5:])
	_, err := rand.Read(id[5:])
	if err != nil {
		panic(err)
	}
	return id
}

func IsKeyViolation(dialect string, errcode string) bool {
	switch dialect {
	case "sqlite":
		return errcode == "1555" || errcode == "2067" // SQLITE_CONSTRAINT_PRIMARYKEY, SQLITE_CONSTRAINT_UNIQUE
	case "postgres":
		return errcode == "23505" // unique_violation
	case "mysql":
		return errcode == "1062" // ER_DUP_ENTRY
	case "sqlserver":
		return errcode == "2627"
	default:
		return false
	}
}

func IsForeignKeyViolation(dialect string, errcode string) bool {
	switch dialect {
	case "sqlite":
		return errcode == "787" //  SQLITE_CONSTRAINT_FOREIGNKEY
	case "postgres":
		return errcode == "23503" // foreign_key_violation
	case "mysql":
		return errcode == "1216" // ER_NO_REFERENCED_ROW
	case "sqlserver":
		return errcode == "547"
	default:
		return false
	}
}

var textExtensions = map[string]bool{
	".html": true,
	".css":  true,
	".js":   true,
	".md":   true,
	".txt":  true,
	".json": true,
	".atom": true,
}

func isFulltextIndexed(filePath string) bool {
	ext := path.Ext(filePath)
	head, tail, _ := strings.Cut(filePath, "/")
	switch head {
	case "notes":
		return ext == ".html" || ext == ".css" || ext == ".js" || ext == ".md" || ext == ".txt"
	case "pages":
		return ext == ".html"
	case "posts":
		return ext == ".md"
	case "output":
		next, _, _ := strings.Cut(tail, "/")
		switch next {
		case "posts":
			return false
		case "themes":
			return ext == ".html" || ext == ".css" || ext == ".js" || ext == ".md" || ext == ".txt"
		default:
			return ext == ".css" || ext == ".js" || ext == ".md"
		}
	}
	return false
}
